### ISSUE TITLE
Cannot connect to multiple clusters

### ISSUE THREAD

**Issue by cah-jeffgraham** [Landoop/kafka-topics-ui#109]
Thanks for providing such a useful tool for viewing topics.  If I use the following in my docker-compose.yml, things work perfectly:

```
   kafka-topic_ui:
    image: landoop/kafka-topics-ui
    container_name: kafka-topic_ui
    hostname: kafka-topic_ui
    depends_on:
      - zookeeper_fronting
      - kafka_fronting
      - zookeeper_consumer
      - kafka_consumer
    ports:
      - "8002:8000"
    environment:
      KAFKA_REST_PROXY_URL: 'http://kafka-rest-proxy_fronting:8092'
      PROXY: 'true'
```

However, I'm having difficulty configuring multiple clusters to connect.  If I make the following change, I cannot connect to either cluster.

```  kafka-topic_ui:
    image: landoop/kafka-topics-ui
    container_name: kafka-topic_ui
    hostname: kafka-topic_ui
    depends_on:
      - zookeeper_fronting
      - kafka_fronting
      - zookeeper_consumer
      - kafka_consumer
    ports:
      - "8002:8000"
    environment:
      PROXY: 'true'
    volumes:
      - ./kafka_topic_ui_env.js:/kafka-topics-ui/env.js
```
contents of kafka_topic_ui_env.js:
```var clusters = [
    {
        NAME: "fronting",
        KAFKA_REST: "http://kafka-rest-proxy_fronting:8092",
        MAX_BYTES: "50000",
        COLOR: "#141414", // Optional
        RECORD_POLL_TIMEOUT: "5000",
        DEBUG_LOGS_ENABLED: true
    },
    {
        NAME: "consumer",
        KAFKA_REST: "http://kafka-rest-proxy_consumer:8093",
        MAX_BYTES: "50000",
        COLOR: "#141414", // Optional
        RECORD_POLL_TIMEOUT: "5000",
        DEBUG_LOGS_ENABLED: true
    }
  ];
```

Error (for both clusters):
```
KAFKA REST
http://kafka-rest-proxy_fronting:8092 
CONNECTIVITY ERROR
```

I'm sure both clusters are running and ports are correct.
