### ISSUE TITLE
Environment variables MAX_BYTES and RECORD_POLL_TIMEOUT do not apply.

### ISSUE THREAD

**Issue by andreasellervee** [Landoop/kafka-topics-ui#148]
Hello

I am using Docker image + Kubernetes to run the Kafka Topics UI.
This is my configuration for Topics UI:
```
        - env:
            - name: KAFKA_REST_PROXY_URL
              value: "http://kafka-rest-proxy:80"
            - name: PROXY
              value: "true"
            - name: PORT
              value: "9094"
            - name: MAX_BYTES
              value: "100000"
            - name: RECORD_POLL_TIMEOUT
              value: "5000"
```

Variables KAFKA_REST_PROXY_URL, PROXY and PORT apply nicely. But the variables MAX_BYTES and RECORD_POLL_TIMEOUT have no effect. The requests are still made with the default 2000 timeout and 50000 bytes.

There are no issues with Kafka Rest Proxy, as making the requests manually via Postman with the timeout and bytes specified works as intended.

All the best,
Andreas
