### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by alifiroozi80** [Landoop/kafka-topics-ui#174]
Hello guys

I want to deploy the Kafka Topic UI with a Docker-Compose file.

Here is my file:

```yaml
version: '3.9'

services:

  # https://github.com/confluentinc/schema-registry
  confluent-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    networks:
      - kafka-topics-ui
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181/kafka
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: "1.1.1.1"
    restart: always

  # https://github.com/confluentinc/kafka-rest
  confluent-rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    networks:
      - kafka-topics-ui
    ports:
      - "8002:8002"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181/kafka
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://0.0.0.0:8081
      KAFKA_REST_HOST_NAME: "1.1.1.1"
    depends_on:
      - confluent-schema-registry
    restart: always
  
  # https://github.com/Landoop/kafka-topics-ui
  kafka-topics-ui:
    image: landoop/kafka-topics-ui:latest
    networks:
      - kafka-topics-ui
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: http://0.0.0.0:8082
      PROXY: "TRUE"
    depends_on:
      - confluent-rest-proxy
    restart: always

networks:
  kafka-topics-ui:
    driver: bridge
```

the `confluent-schema-registry` and `confluent-rest-proxy` comes up without any issue
However, the `kafka-topics-ui` is constantly restarted and exits with this error:

```shell
ubuntu-kafka-topics-ui-1            | panic: 
ubuntu-kafka-topics-ui-1            | runtime error: slice bounds out of range
ubuntu-kafka-topics-ui-1            | 
ubuntu-kafka-topics-ui-1            | goroutine 1 [running]:
ubuntu-kafka-topics-ui-1            | github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xb5fb42, 0x10, 0x0, 0x0, 0x0)
ubuntu-kafka-topics-ui-1            | 	/var/folders/d4/3d8k5bgd62v9h2c5f05xkyx80000gn/T/gopath_02-19-2255.179888757/src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0x9c4
ubuntu-kafka-topics-ui-1            | github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xb5fb42, 0x10, 0xf79b40, 0x2, 0x2, 0xbe7720, 0xc4200822d0, 0xc420063f58)
ubuntu-kafka-topics-ui-1            | 	/var/folders/d4/3d8k5bgd62v9h2c5f05xkyx80000gn/T/gopath_02-19-2255.179888757/src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
ubuntu-kafka-topics-ui-1            | 
ubuntu-kafka-topics-ui-1 exited with code 2
```

---

I think it's an error related to Caddy.
This project hasn't been updated since 2019.
Is this project a Dead Project?
