### ISSUE TITLE
topic-ui cannot fetch topic content

### ISSUE THREAD

**Issue by niklas-ng** [Landoop/kafka-topics-ui#72]
I managed to setup topics-ui to connect with rest proxy and fetch the topic list but the UI does not manage to load the topic's information/content.  The detail setting of dockers are as following:

docker-compose.yml for all the services: 
```services:
  zookeeper:
    image: "confluentinc/cp-zookeeper"
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: "confluentinc/cp-kafka"
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  schema-registry:
    image: "confluentinc/cp-schema-registry"
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
      - kafka
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081

  kafka-rest:
    image: "confluentinc/cp-kafka-rest"
    container_name: kafka-rest
    ports:
      - "8082:8082"
    environment:
     - ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*"
     - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema-registry:8081
     - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_REST_LISTENERS=http://kafka-rest:8082
     - KAFKA_REST_HOST_NAME=kafka-rest
    depends_on:
      - kafka
      - schema-registry
      - zookeeper

  kafka-topic-ui:
    image: "landoop/kafka-topics-ui"
    container_name: kafka-topics-ui
    ports:
      - "8000:8000"
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - SCHEMAREGISTRY_UI_URL=http://schema-registry:8081
      - PROXY=true
    depends_on:
      - kafka
      - schema-registry
      - zookeeper
      - kafka-rest
```

I can see the topics' name on the UI. But when I click on a topic, its details is never loaded:
![topics-ui](https://cloud.githubusercontent.com/assets/28594609/26147569/417dc36a-3af4-11e7-93be-abe16e9ec451.png)

I have tried different options with settings of kafka-rest and schema-registry following [This issue](https://github.com/Landoop/kafka-topics-ui/issues/8) and this [doc](https://github.com/confluentinc/cp-docker-images/blob/master/docs/quickstart.rst) and finally come to this settings. However, it does not seem to work in my case.

Can you advice me on fixing this issue?
Thanks,
/Nhan

**Comment by andmarios** [comment]
Hi @niklas-ng, thank you for reporting this issue.

I gave your docker-compose a try and there indeed seems to be a problem with our latest Kafka Topics UI.

You can use an older version while we investigate this:
```
kafka-topic-ui:
    image: landoop/kafka-topics-ui:0.8.3
```

Thanks,
Marios

**Comment by niklas-ng** [comment]
Hi @andmarios,

I give it a try with "landoop/kafka-topics-ui:0.8.3" but still have the same issue. .

**Comment by andmarios** [comment]
You may need to refresh your tab due to angular. The best way to do this, depends on your browser. If you are on Chrome, open Kafka Topics UI, bring up the developer console (CTRL+SHIFT+i) and then hit refresh (or CTRL+F5).

**Comment by niklas-ng** [comment]
I have tried that, even restarted Chrome and also tried with another browser (MS Edge). It does not help.
On Chrome, I got this error:
```
TypeError: Cannot read property 'trim' of undefined
    at Object.RECORD_POLL_TIMEOUT (combined.js?rel=514ab2234f:576)
    at getRecords (combined.js?rel=514ab2234f:383)
    at combined.js?rel=514ab2234f:280
    at angular.js:16832
    at m.$digest (angular.js:17971)
    at m.$apply (angular.js:18269)
    at l (angular.js:12387)
    at XMLHttpRequest.A.onload (angular.js:12541) "Possibly unhandled rejection: {}"`
```
Note: this error occurs once I just open the topics-ui on browser, not only when I click on a topic.

**Comment by andmarios** [comment]
It seems you are still using the 0.9.2 version of the UI —we know this due to the `514ab2234f` version of the combined.js file. Maybe you didn't run the `docker-compose down` step, so you still use your old containers?

**Comment by niklas-ng** [comment]
I am using version 0.8.3
```
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                        NAMES
fdbb45f8b495        landoop/kafka-topics-ui:0.8.3     "/run.sh"                6 seconds ago       Up 5 seconds        0.0.0.0:8000->8000/tcp                       kafka-topics-ui
53e7e63e047b        confluentinc/cp-kafka-rest        "/etc/confluent/do..."   7 seconds ago       Up 6 seconds        0.0.0.0:8082->8082/tcp                       kafka-rest
2088a63bfd48        confluentinc/cp-schema-registry   "/etc/confluent/do..."   8 seconds ago       Up 7 seconds        0.0.0.0:8081->8081/tcp                       schema-registry
fea046971f0b        confluentinc/cp-kafka             "/etc/confluent/do..."   8 seconds ago       Up 8 seconds        0.0.0.0:9092->9092/tcp                       kafka
4cfbba48e1d4        confluentinc/cp-zookeeper         "/etc/confluent/do..."   9 seconds ago       Up 8 seconds        2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp   zookeeper
```

**Comment by andmarios** [comment]
Ok, but your browser logs indicate the 0.9.2 UI. Could you please try once more the refresh trick? With the developer console open, press CTRL+F5.

I reproduced the problem with the 0.9.2 version and our dev team is already looking into it.
I didn't have any problem with 0.8.3 though. There is a thought that this may be due to some timeout of a slow component, so in principle it could affect 0.8.3 too, though I don't think this is the issue here.

**Comment by niklas-ng** [comment]
Yeah. You are right. I got 0.8.3 UI now and can see the topics. Thanks.

**Comment by andmarios** [comment]
Cool! We will update you when the 0.9.2 version is fixed. It includes some very nice additions.

**Comment by fuyar** [comment]
Hello, did u pinpoint the issue ? I've got the same. 0.8.3 is working but topics are not showed in the homepage. I can still query them directly tho (cluster/default/topic/c/my_topic).

I'm using latest Kafka 0.10.2 so maybe it's not compatible with 0.8.3 ?

**Comment by jglambed** [comment]
This seems like a different issue.
It should be compatible, can you send us console logs so we can look up the error?

**Comment by fuyar** [comment]
Sorry for the false alarm. It was a cache issue on Chrome. It's now working after deleting the cache or within a private session

**Comment by andmarios** [comment]
Ok, solved the issue with the 0.9.2 Topics UI. Our most recent version uses the V2 APIs from REST Proxy. In order to use these, the proxy needs to create a new consumer. To do this, you need one more setting: `bootstrap.servers`.
It is a bit funny of a bootstrap servers strings (includes protocol) but this is the environment   variable you have to add to your REST Proxy (kafka-rest) for the new UI to work:

```
KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
```

**Comment by Antwnis** [comment]
Hi @niklas-ng many thanks for this bug report. We will update README.md and also provide a `docker-compose.yml` as an example on how to set-up Kafka REST correctly in order for Kafka Topics UI >= 0.9.x to work nicely

Don't forget to **star** the projects you like & use 👍

**Comment by Kosta2206** [comment]
Hi, was this already resolved in 0.9.2 ?
Even after specifying bootstrap.servers property, I still have the same issue : 

![image](https://cloud.githubusercontent.com/assets/2376217/26404689/1385510e-4093-11e7-9a16-96883e67b880.png)

**Comment by jglambed** [comment]
Hi @Kosta2206 
I am pretty sure it's a cache issue of `env.js` file.
Can you try force reloading the page(ctrl + f5 should work) and let us know if that worked out?

**Comment by fuyar** [comment]
Just went back to 0.9.2 with adding the bootstrap.server info to my kafka-rest and .. it works! 

Thanks ;)

**Comment by kinghuang** [comment]
I'm having what I think is the same issue. Updated to `0.9.2`, but no messages load when a topic is selected.

I've added the `KAFKA_REST_BOOTSTRAP_SERVERS` environment variable to `kafka-topics-ui`, and the console log seems ok when I select a topic. But, I just get a never-ending progress bar and no messages.

**Excerpt of Docker Compose file**
```
 zookeeper:
    image: zookeeper:3.4.10
    hostname: zookeeper
    networks:
      - streaming

  kafka:
    image: confluentinc/cp-kafka:3.2.1
    hostname: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - streaming
    depends_on:
      - zookeeper

  kafka-rest:
    image: confluentinc/cp-kafka-rest:3.2.1
    hostname: kafka-rest
    environment:
      - ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*"
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_REST_HOST_NAME=kafka-rest
      - KAFKA_REST_LISTENERS=http://kafka-rest:8082
    networks:
      - streaming
    depends_on:
      - zookeeper
      - kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:3.2.1
    hostname: schema-registry
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
    networks:
      - streaming
    depends_on:
      - zookeeper
      - kafka

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.2
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
      - PROXY=true
    ports:
      - 8001:8000
    networks:
      - streaming
```

**Console logs when a topic is selected**
```
[Debug] converis.Country – "POLL STEPS START" (angular.min.js, line 123)
[Debug] converis.Country (2) (angular.min.js, line 123)
"1) DONE: GOT ALL PARTITIONS"
{data: Array, status: 200, headers: function, config: Object, statusText: "OK"}
[Debug] converis.Country (2) (angular.min.js, line 123)
"2) ACTUAL PARTITIONS TO ASSIGN"
{partitions: [{topic: "converis.Country", partition: 0}]}
[Debug] converis.Country – "3) DONE: ASSIGNED PARTITIONS TO CONSUMER" (angular.min.js, line 123)
[Debug] converis.Country – "4) SEEK TO BEGGINING FOR ALL PARTITIONS DONE" (angular.min.js, line 123)
[Debug] converis.Country (2) (angular.min.js, line 123)
"5) START POLLING WITH CONSUMER:"
{group: "kafka_topics_ui_avro_2017-05-29-01-11-33-395", instance: "kafka-topics-ui-avro"}
```

What am I missing?
